########################################
# LABOPS CONFIGURATION
########################################

LABOPS_VERSION=1.0

HOSTNAME=srv.lab

MODE=lite

TIMEZONE=America/Sao_Paulo

ENABLE_DOCKER=true
ENABLE_GRAFANA=false
ENABLE_POSTGRES=true
ENABLE_MYSQL=false
ENABLE_REDIS=false
ENABLE_AI=false
ENABLE_MONITOR=true

DATA_DIR=/opt/labops/data

BACKUP_DIR=/opt/labops/backups

LOG_DIR=/opt/labops/logs
